### ISSUE TITLE
PW 3.0 Issues

### ISSUE THREAD

**Issue by thetuningspoon** [kixe/ProcessSetupPageName#1]
Tried this out in PW 3.0 and ran into some issues with the code. Specifically, it didn't like the reference to "self" within the anonymous hook functions. To fix it, I switched the hooks from anonymous to the traditional hook style:

`/**
    public function init() {
        $this->addHookBefore('Pages::setupPageName', $this, 'hookBeforeSetupPageName');
        $this->addHookAfter('ProcessTemplate::buildEditForm', $this, 'hookAfterBuildEditForm');
        if (wire('modules')->isInstalled('InputfieldPageTable')) {
            $this->addHookAfter('InputfieldPageTable::getConfigInputfields', $this, 'hookAfterGetConfigInputfields');
        }

```
    self::$notes = $this->_('Leave blank to disable. Enter any fieldname, subfield, property or date() function separated by space. Dot syntax allowed. Example: \'parent.title date(Y) myfield\' (without quotes) will auto-generate the name from the title of page parent, the current year and the value of pagefield \'myfield\' [More](https://processwire.com/talk/topic/8576-name-format-children/?p=108748)');
}

public function hookBeforeSetupPageName($event) {
    $page = $event->arguments[0];
    $event->replace = true;
    $options = count($event->arguments) == 2 ? $event->arguments[1] : array();
    $name = wire('modules')->get('ProcessSetupPageName')->SetupPageName($page, $options);
    $event->return = $name;
}

public function hookAfterBuildEditForm($event) {
    $return = $event->return;
    $return->children()->get(2)->children()->first()->children()->get('childNameFormat')->set('notes',self::$notes);
    $event->return = $return;
}


public function hookAfterGetConfigInputfields($event) {
    $return = $event->return;
    $return->children()->get('nameFormat')->set('notes',self::$notes);
    $event->return = $return;
}`
```

**Comment by thetuningspoon** [comment]
An update... The reason for this was not PW 3, but the fact that I am using a version of php which is older than 5.4. Older versions of php consider anonymous functions to be outside of the scope of the class.

**Comment by kixe** [comment]
Thanks for pointing this out. I will add: 'PHP>=5.4.1'
