### ISSUE TITLE
Error: Call to a member function getLanguageValue() on non-object 

### ISSUE THREAD

**Issue by Sebastyle** [kixe/ProcessSetupPageName#2]
Since update from 1.1.1 to 2.0 of the module, I get the mentioned error message when creating a new page using the module! Processwire Version is 2.7.2

Relevant code lines are: https://github.com/kixe/ProcessSetupPageName/blob/master/ProcessSetupPageName.module#L121-L122
The "name formatfor children" of the parent is setup as: "date('y') date('m') title", which worked fine with 1.1.1

I think that the solution should be to just check if $page->title is set, only then use getLanguageValue().

**Comment by kixe** [comment]
This repository is no longer maintained as it has been fully implemented in ProcessWire core.
